"""Core data types for the backtesting platform.

All types are immutable (frozen dataclasses) to prevent accidental mutation
during simulation. The backtester creates new instances each step.
"""
from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from datetime import date
from enum import Enum
from typing import Any, Dict, FrozenSet, List, Optional, Sequence, Tuple

import pandas as pd


class OrderSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderStatus(str, Enum):
    PENDING = "PENDING"
    FILLED = "FILLED"
    PARTIAL = "PARTIAL"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class FillType(str, Enum):
    MARKET_OPEN = "MARKET_OPEN"
    MARKET_CLOSE = "MARKET_CLOSE"
    VWAP = "VWAP"
    LIMIT = "LIMIT"


@dataclass(frozen=True)
class Order:
    """A simulated order generated by the execution layer."""
    symbol: str
    side: OrderSide
    notional: float
    shares: float = 0.0
    strategy_id: str = ""
    reason: str = ""
    created_date: Optional[pd.Timestamp] = None
    order_id: str = ""

    #: "Sell the whole position", not "sell this many shares". The broker skips
    #: whole-share rounding for these, because you can always sell exactly what
    #: you hold. Rounding a full exit down strands a fraction of a share, the
    #: position never closes, and the engine re-issues the same exit every
    #: session forever -- see ``broker._floor_whole_shares``. Share counts are
    #: held on the adjusted scale, so ``shares * factor`` is only an integer when
    #: no corporate action has intervened; a dividend payer held across its
    #: ex-date lands between two whole raw shares and cannot be closed by
    #: flooring at all.
    close_position: bool = False


@dataclass(frozen=True)
class Fill:
    """A simulated fill from the broker."""
    order: Order
    fill_price: float
    fill_shares: float
    fill_date: pd.Timestamp
    commission: float = 0.0
    slippage_bps: float = 0.0
    fill_type: FillType = FillType.MARKET_OPEN
    fill_id: str = ""


@dataclass(frozen=True)
class Lot:
    """A FIFO lot for position tracking.

    ``shares`` is signed: negative is a short. One field rather than a separate
    side, because every piece of arithmetic downstream -- market value, unrealized
    PnL, gross exposure -- then works for both directions without branching, and a
    branch that exists in five places is a branch that will be forgotten in one.
    """
    symbol: str
    shares: float
    entry_price: float
    entry_date: pd.Timestamp
    strategy_id: str = ""
    lot_id: str = ""

    @property
    def is_short(self) -> bool:
        return self.shares < 0


@dataclass(frozen=True)
class Position:
    """Aggregate position in a symbol (sum of lots).

    ``shares`` and ``market_value`` are signed. A short shows negative for both,
    which is what makes equity add up: shorting $5,000 credits $5,000 of cash and
    books -$5,000 of market value, so equity is unchanged at the moment of sale
    and moves only as the price does.
    """
    symbol: str
    shares: float
    avg_entry_price: float
    market_price: float
    market_value: float
    unrealized_pnl: float
    entry_date: pd.Timestamp  # earliest lot entry
    lots: Tuple[Lot, ...] = ()

    @property
    def is_short(self) -> bool:
        return self.shares < 0

    @property
    def exposure(self) -> float:
        """Absolute market value, which is what a risk limit cares about."""
        return abs(self.market_value)


@dataclass(frozen=True)
class PortfolioSnapshot:
    """Full portfolio state at a point in time."""
    date: pd.Timestamp
    cash: float
    equity: float  # cash + sum(market_values)
    positions: Dict[str, Position] = field(default_factory=dict)
    realized_pnl: float = 0.0
    unrealized_pnl: float = 0.0
    strategy_id: str = ""

    @property
    def market_value(self) -> float:
        """Net market value: longs minus shorts."""
        return sum(p.market_value for p in self.positions.values())

    @property
    def long_value(self) -> float:
        return sum(p.market_value for p in self.positions.values() if p.market_value > 0)

    @property
    def short_value(self) -> float:
        """Absolute value of the short book, as a positive number."""
        return sum(
            -p.market_value for p in self.positions.values() if p.market_value < 0
        )

    @property
    def gross_value(self) -> float:
        """Longs plus shorts. What leverage and borrow fees are measured on."""
        return self.long_value + self.short_value

    @property
    def position_count(self) -> int:
        return len(self.positions)

    @property
    def symbols(self) -> FrozenSet[str]:
        return frozenset(self.positions.keys())

    @property
    def short_symbols(self) -> FrozenSet[str]:
        return frozenset(
            s for s, p in self.positions.items() if p.market_value < 0
        )

    @property
    def weights(self) -> Dict[str, float]:
        """Signed weights: a short is negative.

        Note that these sum to *net* exposure, not gross. A market-neutral book
        sums to roughly zero while carrying 2x gross, so a caller checking
        leverage must use ``gross_value`` or take absolute values -- summing these
        would report a fully levered long/short fund as flat.
        """
        if self.equity <= 0:
            return {}
        return {sym: pos.market_value / self.equity for sym, pos in self.positions.items()}

    def margin_requirement(self, config: "ShortConfig") -> float:
        """Equity the broker requires against this book, at maintenance rates."""
        return (
            self.long_value * config.maintenance_margin_long
            + self.short_value * config.maintenance_margin_short
        )


@dataclass(frozen=True)
class CostConfig:
    """Transaction cost assumptions."""
    spread_bps: float = 5.0        # bid-ask spread in basis points
    slippage_bps: float = 5.0      # market impact in basis points
    commission_per_share: float = 0.0  # Alpaca = $0 for equities
    min_commission: float = 0.0
    participation_rate: float = 0.05   # max fraction of daily volume per order
    borrow_rate_annual: float = 0.0    # for short positions (future)

    @property
    def total_one_way_bps(self) -> float:
        return self.spread_bps / 2 + self.slippage_bps


@dataclass(frozen=True)
class RiskConfig:
    """Risk management rules."""
    max_position_pct: float = 0.20      # max single position as % of equity
    max_sector_pct: float = 0.40        # max sector exposure
    cash_reserve_pct: float = 0.10      # minimum cash reserve
    max_leverage: float = 1.0           # no leverage by default
    max_positions: int = 50
    fractional_shares: bool = False     # whole shares by default

    #: Cap on the short book as a share of equity. None means only the gross
    #: leverage limit applies. Kept separate from ``max_leverage`` because the two
    #: constrain different risks: a long leg can lose its capital, a short leg has
    #: no such floor, so a fund can reasonably permit more gross than short.
    max_short_pct: Optional[float] = None


@dataclass(frozen=True)
class ShortConfig:
    """Short-side assumptions.

    Off by default. Every long-only strategy in this repository behaves exactly as
    before unless ``allow_shorts`` is set, because a negative target weight is
    otherwise dropped rather than silently reinterpreted.

    The borrow model is the honest weak point. Real borrow rates are a daily,
    per-name, broker-specific quote and no free source publishes history for them,
    so what is modelled here is a *policy*: a flat rate for general collateral, a
    higher flat rate for a named hard-to-borrow set, and an unborrowable set that
    cannot be shorted at all. That is a fiction with the right shape, not a
    reconstruction, and any short backtest has to be read with that in mind --
    which is why every run records it and ``BacktestResult.limitations`` says so.
    """
    allow_shorts: bool = False

    #: Annualized borrow fee on general collateral. 1% is a reasonable stand-in
    #: for a liquid large-cap; the number that matters is that it is not zero.
    borrow_rate_annual: float = 0.01

    #: Annualized borrow fee for names in ``hard_to_borrow``. Real HTB names run
    #: anywhere from 5% to over 100%; 20% is a deliberately uncomfortable default,
    #: because a short thesis that only works at general-collateral rates is not a
    #: short thesis.
    hard_to_borrow_rate_annual: float = 0.20
    hard_to_borrow: FrozenSet[str] = frozenset()

    #: Cannot be shorted at all. An existing short in one of these is bought in.
    unborrowable: FrozenSet[str] = frozenset()

    #: Reg T initial margin. A long needs 50% of its value in equity; a short
    #: needs 150% of the proceeds on deposit, which is the proceeds themselves
    #: plus 50% -- so the *additional* equity required is 50%.
    initial_margin_long: float = 0.50
    initial_margin_short: float = 0.50

    #: Maintenance margin, below which the broker liquidates. Typical house
    #: requirements, stricter on the short side because losses are unbounded.
    maintenance_margin_long: float = 0.25
    maintenance_margin_short: float = 0.30

    #: Whether short-sale proceeds earn interest. Retail accounts get nothing, so
    #: the default is False; a prime-brokered fund would set a rebate rate.
    short_proceeds_earn_interest: bool = False
    short_rebate_annual: float = 0.0

    def borrow_rate(self, symbol: str) -> float:
        """Annualized borrow fee for one symbol."""
        return (
            self.hard_to_borrow_rate_annual
            if symbol.upper() in self.hard_to_borrow
            else self.borrow_rate_annual
        )

    def borrowable(self, symbol: str) -> bool:
        return symbol.upper() not in self.unborrowable


@dataclass(frozen=True)
class ExecutionConfig:
    """Execution assumptions."""
    fill_type: FillType = FillType.MARKET_OPEN  # fill at next day's open
    fill_delay_days: int = 1                     # D+1
    fractional_shares: bool = False
    delisting_return: float = -0.30              # Shumway's -30% haircut


@dataclass(frozen=True)
class BacktestConfig:
    """Complete configuration for a backtest run."""
    strategy_id: str
    strategy_module: str
    start_date: str                  # YYYY-MM-DD
    end_date: str                    # YYYY-MM-DD
    initial_capital: float = 100_000.0
    benchmark: str = "SPY"

    cost: CostConfig = field(default_factory=CostConfig)
    risk: RiskConfig = field(default_factory=RiskConfig)
    execution: ExecutionConfig = field(default_factory=ExecutionConfig)
    short: ShortConfig = field(default_factory=ShortConfig)

    params: Dict[str, Any] = field(default_factory=dict)
    universe_source: str = "pit_sp500"  # or "current", "etf_rotation", custom
    price_source: str = "lake"

    #: How ``adj_close`` levels are anchored. ``"asof"`` re-anchors the
    #: adjustment to ``end_date`` so the run cannot see corporate actions that
    #: postdate the test window; ``"today"`` uses the lake as stored, which is
    #: back-adjusted to the download date. Either way, level-sensitive decisions
    #: should read the raw print (``ctx.raw_close``) -- see
    #: ``data_pipeline.adjust``.
    price_adjustment: str = "asof"

    # Metadata
    git_commit: str = ""
    data_vintage: str = ""
    trial_index: int = 0
    random_seed: int = 42
    notes: str = ""

    def run_id(self) -> str:
        """Deterministic run identifier from config hash."""
        key_parts = f"{self.strategy_id}:{self.start_date}:{self.end_date}:{self.initial_capital}"
        key_parts += f":{json.dumps(self.params, sort_keys=True)}"
        return hashlib.sha256(key_parts.encode()).hexdigest()[:12]


@dataclass
class BacktestResult:
    """Complete output of a backtest run."""
    config: BacktestConfig

    # Time series
    equity_curve: pd.Series = field(default_factory=lambda: pd.Series(dtype=float))
    returns: pd.Series = field(default_factory=lambda: pd.Series(dtype=float))
    benchmark_equity: pd.Series = field(default_factory=lambda: pd.Series(dtype=float))
    benchmark_returns: pd.Series = field(default_factory=lambda: pd.Series(dtype=float))

    # Logs
    orders: List[Order] = field(default_factory=list)
    fills: List[Fill] = field(default_factory=list)
    snapshots: List[PortfolioSnapshot] = field(default_factory=list)

    # Aggregated
    metrics: Dict[str, Any] = field(default_factory=dict)

    # Metadata
    run_id: str = ""
    started_at: str = ""
    finished_at: str = ""
    elapsed_seconds: float = 0.0
    warnings: List[str] = field(default_factory=list)
    limitations: List[str] = field(default_factory=list)
