"""Core data types for the backtesting platform.

All types are immutable (frozen dataclasses) to prevent accidental mutation
during simulation. The backtester creates new instances each step.
"""
from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from datetime import date
from enum import Enum
from typing import Any, Dict, FrozenSet, List, Optional, Sequence, Tuple

import pandas as pd


class OrderSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderStatus(str, Enum):
    PENDING = "PENDING"
    FILLED = "FILLED"
    PARTIAL = "PARTIAL"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class FillType(str, Enum):
    MARKET_OPEN = "MARKET_OPEN"
    MARKET_CLOSE = "MARKET_CLOSE"
    VWAP = "VWAP"
    LIMIT = "LIMIT"


@dataclass(frozen=True)
class Order:
    """A simulated order generated by the execution layer."""
    symbol: str
    side: OrderSide
    notional: float
    shares: float = 0.0
    strategy_id: str = ""
    reason: str = ""
    created_date: Optional[pd.Timestamp] = None
    order_id: str = ""

    #: "Sell the whole position", not "sell this many shares". The broker skips
    #: whole-share rounding for these, because you can always sell exactly what
    #: you hold. Rounding a full exit down strands a fraction of a share, the
    #: position never closes, and the engine re-issues the same exit every
    #: session forever -- see ``broker._floor_whole_shares``. Share counts are
    #: held on the adjusted scale, so ``shares * factor`` is only an integer when
    #: no corporate action has intervened; a dividend payer held across its
    #: ex-date lands between two whole raw shares and cannot be closed by
    #: flooring at all.
    close_position: bool = False


@dataclass(frozen=True)
class Fill:
    """A simulated fill from the broker."""
    order: Order
    fill_price: float
    fill_shares: float
    fill_date: pd.Timestamp
    commission: float = 0.0
    slippage_bps: float = 0.0
    fill_type: FillType = FillType.MARKET_OPEN
    fill_id: str = ""


@dataclass(frozen=True)
class Lot:
    """A FIFO lot for position tracking."""
    symbol: str
    shares: float
    entry_price: float
    entry_date: pd.Timestamp
    strategy_id: str = ""
    lot_id: str = ""


@dataclass(frozen=True)
class Position:
    """Aggregate position in a symbol (sum of lots)."""
    symbol: str
    shares: float
    avg_entry_price: float
    market_price: float
    market_value: float
    unrealized_pnl: float
    entry_date: pd.Timestamp  # earliest lot entry
    lots: Tuple[Lot, ...] = ()


@dataclass(frozen=True)
class PortfolioSnapshot:
    """Full portfolio state at a point in time."""
    date: pd.Timestamp
    cash: float
    equity: float  # cash + sum(market_values)
    positions: Dict[str, Position] = field(default_factory=dict)
    realized_pnl: float = 0.0
    unrealized_pnl: float = 0.0
    strategy_id: str = ""

    @property
    def market_value(self) -> float:
        return sum(p.market_value for p in self.positions.values())

    @property
    def position_count(self) -> int:
        return len(self.positions)

    @property
    def symbols(self) -> FrozenSet[str]:
        return frozenset(self.positions.keys())

    @property
    def weights(self) -> Dict[str, float]:
        if self.equity <= 0:
            return {}
        return {sym: pos.market_value / self.equity for sym, pos in self.positions.items()}


@dataclass(frozen=True)
class CostConfig:
    """Transaction cost assumptions."""
    spread_bps: float = 5.0        # bid-ask spread in basis points
    slippage_bps: float = 5.0      # market impact in basis points
    commission_per_share: float = 0.0  # Alpaca = $0 for equities
    min_commission: float = 0.0
    participation_rate: float = 0.05   # max fraction of daily volume per order
    borrow_rate_annual: float = 0.0    # for short positions (future)

    @property
    def total_one_way_bps(self) -> float:
        return self.spread_bps / 2 + self.slippage_bps


@dataclass(frozen=True)
class RiskConfig:
    """Risk management rules."""
    max_position_pct: float = 0.20      # max single position as % of equity
    max_sector_pct: float = 0.40        # max sector exposure
    cash_reserve_pct: float = 0.10      # minimum cash reserve
    max_leverage: float = 1.0           # no leverage by default
    max_positions: int = 50
    fractional_shares: bool = False     # whole shares by default


@dataclass(frozen=True)
class ExecutionConfig:
    """Execution assumptions."""
    fill_type: FillType = FillType.MARKET_OPEN  # fill at next day's open
    fill_delay_days: int = 1                     # D+1
    fractional_shares: bool = False
    delisting_return: float = -0.30              # Shumway's -30% haircut


@dataclass(frozen=True)
class BacktestConfig:
    """Complete configuration for a backtest run."""
    strategy_id: str
    strategy_module: str
    start_date: str                  # YYYY-MM-DD
    end_date: str                    # YYYY-MM-DD
    initial_capital: float = 100_000.0
    benchmark: str = "SPY"

    cost: CostConfig = field(default_factory=CostConfig)
    risk: RiskConfig = field(default_factory=RiskConfig)
    execution: ExecutionConfig = field(default_factory=ExecutionConfig)

    params: Dict[str, Any] = field(default_factory=dict)
    universe_source: str = "pit_sp500"  # or "current", "etf_rotation", custom
    price_source: str = "lake"

    #: How ``adj_close`` levels are anchored. ``"asof"`` re-anchors the
    #: adjustment to ``end_date`` so the run cannot see corporate actions that
    #: postdate the test window; ``"today"`` uses the lake as stored, which is
    #: back-adjusted to the download date. Either way, level-sensitive decisions
    #: should read the raw print (``ctx.raw_close``) -- see
    #: ``data_pipeline.adjust``.
    price_adjustment: str = "asof"

    # Metadata
    git_commit: str = ""
    data_vintage: str = ""
    trial_index: int = 0
    random_seed: int = 42
    notes: str = ""

    def run_id(self) -> str:
        """Deterministic run identifier from config hash."""
        key_parts = f"{self.strategy_id}:{self.start_date}:{self.end_date}:{self.initial_capital}"
        key_parts += f":{json.dumps(self.params, sort_keys=True)}"
        return hashlib.sha256(key_parts.encode()).hexdigest()[:12]


@dataclass
class BacktestResult:
    """Complete output of a backtest run."""
    config: BacktestConfig

    # Time series
    equity_curve: pd.Series = field(default_factory=lambda: pd.Series(dtype=float))
    returns: pd.Series = field(default_factory=lambda: pd.Series(dtype=float))
    benchmark_equity: pd.Series = field(default_factory=lambda: pd.Series(dtype=float))
    benchmark_returns: pd.Series = field(default_factory=lambda: pd.Series(dtype=float))

    # Logs
    orders: List[Order] = field(default_factory=list)
    fills: List[Fill] = field(default_factory=list)
    snapshots: List[PortfolioSnapshot] = field(default_factory=list)

    # Aggregated
    metrics: Dict[str, Any] = field(default_factory=dict)

    # Metadata
    run_id: str = ""
    started_at: str = ""
    finished_at: str = ""
    elapsed_seconds: float = 0.0
    warnings: List[str] = field(default_factory=list)
    limitations: List[str] = field(default_factory=list)
